import assert from "node:assert/strict";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";

import {
  PNG_SIGNATURE,
  REQUIRED_ASSET_INVENTORY,
  exportDeclaredAssets,
  readPngDimensions,
  renderSvgToPng,
  validateAssetManifest,
  validateSvgSource,
} from "../../scripts/export-assets.mjs";
import { verifyDeclaredAssetOutputs } from "../../scripts/verify-assets.mjs";

function createAssetRecord(assetId, requirement) {
  const outputs = requirement.requiredOutputDimensions.map((dimensions, outputIndex) => ({
    path: `public/generated/${assetId}-${outputIndex}-${dimensions.width}x${dimensions.height}.png`,
    width: dimensions.width,
    height: dimensions.height,
  }));
  const informative = requirement.kind === "diagram" || requirement.kind === "social";

  return {
    assetId,
    kind: requirement.kind,
    sourcePath: requirement.sourcePath,
    outputs,
    locale: assetId === "social-default-en"
      ? "en"
      : assetId === "social-default-zh"
        ? "zh"
        : null,
    altKey: informative ? `assets.${assetId}.alt` : null,
    decorative: !informative,
    originalityNote: "Original project-owned work; no retired website asset was referenced.",
  };
}

function createCompleteManifest() {
  return {
    assets: Object.entries(REQUIRED_ASSET_INVENTORY).map(([assetId, requirement]) =>
      createAssetRecord(assetId, requirement),
    ),
  };
}

function createFixtureManifest() {
  return {
    assets: [
      {
        assetId: "fixture-square",
        kind: "favicon",
        sourcePath: "public/icons/fixture-square.svg",
        outputs: [
          {
            path: "public/icons/fixture-square-32.png",
            width: 32,
            height: 32,
          },
        ],
        locale: null,
        altKey: null,
        decorative: true,
        originalityNote: "Original fixture generated by the Node test.",
      },
    ],
  };
}

const SQUARE_SVG = `
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
  <rect width="32" height="32" fill="#123b5d"/>
  <path d="M8 16h16M16 8v16" stroke="#ffffff" stroke-width="2"/>
</svg>
`;

const FONT_DEPENDENT_SVG = `
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
  <rect width="32" height="32" fill="#123b5d"/>
  <text x="4" y="20" font-family="sans-serif" font-size="12">Test</text>
</svg>
`;

test("accepts the complete required inventory and schema", () => {
  const validation = validateAssetManifest(createCompleteManifest());
  assert.deepEqual(validation.errors, []);
});

test("reports missing required inventory and malformed fields", () => {
  const validation = validateAssetManifest({
    assets: [
      {
        assetId: "broken",
        kind: "unknown",
        sourcePath: "../outside.svg",
        outputs: [{ path: "output.jpg", width: 0, height: "32" }],
        locale: "unsupported",
        decorative: false,
      },
    ],
  });

  assert.equal(validation.errors.some((error) => error.includes("Required brand asset")), true);
  assert.equal(validation.errors.some((error) => error.includes("safe website-relative SVG")), true);
  assert.equal(validation.errors.some((error) => error.includes("altKey is required")), true);
  assert.equal(validation.errors.some((error) => error.includes("ownership")), true);
});

test("renders deterministic PNG bytes with the declared dimensions", () => {
  const firstPng = renderSvgToPng(SQUARE_SVG, { width: 32, height: 32 });
  const secondPng = renderSvgToPng(SQUARE_SVG, { width: 32, height: 32 });

  assert.equal(firstPng.equals(secondPng), true);
  assert.equal(firstPng.subarray(0, PNG_SIGNATURE.length).equals(PNG_SIGNATURE), true);
  assert.deepEqual(readPngDimensions(firstPng), { width: 32, height: 32 });
});

test("rejects unsafe or non-scalable SVG sources", () => {
  assert.deepEqual(validateSvgSource(SQUARE_SVG), []);

  const unsafeSvg =
    '<svg xmlns="http://www.w3.org/2000/svg"><script>alert(1)</script><image href="https://example.invalid/image.png"/></svg>';
  const errors = validateSvgSource(unsafeSvg, "unsafe.svg");

  assert.equal(errors.some((error) => error.includes("viewBox")), true);
  assert.equal(errors.some((error) => error.includes("scripts")), true);
  assert.equal(errors.some((error) => error.includes("remote linked resources")), true);
});

test("exports and verifies declared raster outputs in a fixture website", async () => {
  const websiteRoot = await mkdtemp(path.join(os.tmpdir(), "oryxos-assets-"));
  const sourcePath = path.join(websiteRoot, "public", "icons", "fixture-square.svg");
  try {
    await mkdir(path.dirname(sourcePath), { recursive: true });
    await writeFile(sourcePath, SQUARE_SVG);

    const manifest = createFixtureManifest();
    const firstExport = await exportDeclaredAssets({
      websiteRoot,
      manifest,
      requireCompleteInventory: false,
    });
    const outputPath = path.join(
      websiteRoot,
      "public",
      "icons",
      "fixture-square-32.png",
    );
    const firstBytes = await readFile(outputPath);
    const secondExport = await exportDeclaredAssets({
      websiteRoot,
      manifest,
      requireCompleteInventory: false,
    });
    const secondBytes = await readFile(outputPath);
    const verification = await verifyDeclaredAssetOutputs({
      websiteRoot,
      manifest,
      requireCompleteInventory: false,
    });

    assert.equal(firstBytes.equals(secondBytes), true);
    assert.equal(firstExport.length, 1);
    assert.equal(secondExport.length, 1);
    assert.deepEqual(verification.errors, []);
    assert.deepEqual(
      verification.outputs.map(({ width, height }) => ({ width, height })),
      [{ width: 32, height: 32 }],
    );
  } finally {
    await rm(websiteRoot, { recursive: true, force: true });
  }
});

test("rejects raster exports that depend on machine-specific SVG fonts", async () => {
  const websiteRoot = await mkdtemp(path.join(os.tmpdir(), "oryxos-assets-font-dependent-"));
  const sourcePath = path.join(websiteRoot, "public", "icons", "fixture-square.svg");

  try {
    await mkdir(path.dirname(sourcePath), { recursive: true });
    await writeFile(sourcePath, FONT_DEPENDENT_SVG);

    await assert.rejects(
      () =>
        exportDeclaredAssets({
          websiteRoot,
          manifest: createFixtureManifest(),
          requireCompleteInventory: false,
        }),
      /contains SVG text.*machine-specific fonts/s,
    );
  } finally {
    await rm(websiteRoot, { recursive: true, force: true });
  }
});

test("verification rejects bad signatures and wrong dimensions", async () => {
  const websiteRoot = await mkdtemp(path.join(os.tmpdir(), "oryxos-assets-invalid-"));
  const sourcePath = path.join(websiteRoot, "public", "icons", "fixture-square.svg");
  const outputPath = path.join(websiteRoot, "public", "icons", "fixture-square-32.png");
  const manifest = createFixtureManifest();

  try {
    await mkdir(path.dirname(sourcePath), { recursive: true });
    await writeFile(sourcePath, SQUARE_SVG);
    await writeFile(outputPath, Buffer.from("not a png"));

    const badSignature = await verifyDeclaredAssetOutputs({
      websiteRoot,
      manifest,
      requireCompleteInventory: false,
    });
    assert.equal(
      badSignature.errors.some((error) => error.includes("too short") || error.includes("signature")),
      true,
    );

    await writeFile(outputPath, renderSvgToPng(SQUARE_SVG, { width: 16, height: 16 }));
    const wrongDimensions = await verifyDeclaredAssetOutputs({
      websiteRoot,
      manifest,
      requireCompleteInventory: false,
    });
    assert.equal(wrongDimensions.errors.some((error) => error.includes("manifest requires 32x32")), true);
  } finally {
    await rm(websiteRoot, { recursive: true, force: true });
  }
});
